import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";

//@ts-ignore
const Navbar = dynamic(() => import("frontend_one/nav"), {
  ssr: false,
});
//@ts-ignore
const Footer = dynamic(() => import("frontend_two/footer"), {
  ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Frontend Three <small>(consumer)</small>
        </h1>
      </main>
      <Footer />
    </div>
  );
}
